-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 22:32:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tfgbbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tfgbbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tfgbbdd` DEFAULT CHARACTER SET utf8 ;
USE `tfgbbdd` ;

-- -----------------------------------------------------
-- Table `tfgbbdd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfgbbdd`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfgbbdd`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfgbbdd`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfgbbdd`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfgbbdd`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_curso_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_curso_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `tfgbbdd`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `tfgbbdd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfgbbdd`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfgbbdd`.`comentario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCurso` VARCHAR(45) NOT NULL,
  `comentario` LONGTEXT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `comentarista_id1` INT NOT NULL,
  `aceptado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_comentario_usuarios2_idx` (`comentarista_id1` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `tfgbbdd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuarios2`
    FOREIGN KEY (`comentarista_id1`)
    REFERENCES `tfgbbdd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfgbbdd`.`cursando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfgbbdd`.`cursando` (
  `idcursando` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idcursando`),
  INDEX `fk_cursando_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_cursando_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursando_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `tfgbbdd`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursando_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `tfgbbdd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tfgbbdd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `tfgbbdd`;
INSERT INTO `tfgbbdd`.`usuarios` (`id`, `nombre`, `correo`, `contrasena`) VALUES (1, 'roman', 'roman.hernandez.dosa@gmail.com', '123');
INSERT INTO `tfgbbdd`.`usuarios` (`id`, `nombre`, `correo`, `contrasena`) VALUES (2, 'jose', 'joseantonio.priego.dosa@gmail.com', '123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tfgbbdd`.`categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `tfgbbdd`;
INSERT INTO `tfgbbdd`.`categoria` (`id`, `nombre`) VALUES (1, 'matemáticas');
INSERT INTO `tfgbbdd`.`categoria` (`id`, `nombre`) VALUES (2, 'programación');

COMMIT;

